import { User, Property, Booking } from './types';

export const MOCK_USERS: User[] = [
  {
    id: 'u1-host-ana',
    email: 'ana@example.com',
    passwordHash: '$2b$12$mock.mock.ana',
    firstName: 'Ana',
    lastName: 'Costa',
    phone: '+5521999990001',
    dateOfBirth: '1985-03-12',
    profilePhotoUrl:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
    bio: 'Anfitriã apaixonada por receber bem. Superhost há 3 anos.',
    language: 'pt-BR',
    currency: 'BRL',
    role: 'host',
    isEmailVerified: true,
    isPhoneVerified: true,
    isIdentityVerified: true,
    isSuperhost: true,
    accountStatus: 'active',
    lastLoginAt: '2026-02-06T10:00:00Z',
    createdAt: '2023-01-15T10:00:00Z',
    updatedAt: '2026-02-06T10:00:00Z',
  },
  {
    id: 'u2-host-carlos',
    email: 'carlos@example.com',
    passwordHash: '$2b$12$mock.mock.carlos',
    firstName: 'Carlos',
    lastName: 'Mendes',
    phone: '+5511999990002',
    dateOfBirth: '1990-07-22',
    profilePhotoUrl:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    bio: 'Proprietário de imóveis em São Paulo e Gramado.',
    language: 'pt-BR',
    currency: 'BRL',
    role: 'host',
    isEmailVerified: true,
    isPhoneVerified: true,
    isIdentityVerified: true,
    isSuperhost: false,
    accountStatus: 'active',
    lastLoginAt: '2026-02-05T18:00:00Z',
    createdAt: '2023-06-10T08:00:00Z',
    updatedAt: '2026-02-05T18:00:00Z',
  },
  {
    id: 'u3-guest-maria',
    email: 'maria@example.com',
    passwordHash: '$2b$12$mock.mock.maria',
    firstName: 'Maria',
    lastName: 'Santos',
    phone: '+5531999990003',
    dateOfBirth: '1995-11-30',
    profilePhotoUrl:
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
    bio: 'Viajante frequente, adora conhecer novos lugares.',
    language: 'pt-BR',
    currency: 'BRL',
    role: 'guest',
    isEmailVerified: true,
    isPhoneVerified: true,
    isIdentityVerified: false,
    isSuperhost: false,
    accountStatus: 'active',
    lastLoginAt: '2026-02-06T14:00:00Z',
    createdAt: '2024-03-20T12:00:00Z',
    updatedAt: '2026-02-06T14:00:00Z',
  },
  {
    id: 'u4-guest-pedro',
    email: 'pedro@example.com',
    passwordHash: '$2b$12$mock.mock.pedro',
    firstName: 'Pedro',
    lastName: 'Oliveira',
    phone: '+5548999990004',
    profilePhotoUrl:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
    bio: 'Nômade digital, trabalho remoto pelo Brasil.',
    language: 'pt-BR',
    currency: 'BRL',
    role: 'guest',
    isEmailVerified: true,
    isPhoneVerified: false,
    isIdentityVerified: false,
    isSuperhost: false,
    accountStatus: 'active',
    lastLoginAt: '2026-02-04T09:00:00Z',
    createdAt: '2024-08-05T16:00:00Z',
    updatedAt: '2026-02-04T09:00:00Z',
  },
  {
    id: 'u5-admin',
    email: 'admin@nomadia.com',
    passwordHash: '$2b$12$mock.mock.admin',
    firstName: 'Admin',
    lastName: 'Nomadia',
    language: 'pt-BR',
    currency: 'BRL',
    role: 'admin',
    isEmailVerified: true,
    isPhoneVerified: true,
    isIdentityVerified: true,
    isSuperhost: false,
    accountStatus: 'active',
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2026-02-06T00:00:00Z',
  },
];

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'p1',
    hostId: 'u1-host-ana',
    title: 'Apartamento com Vista para o Mar em Copacabana',
    description:
      'Lindo apartamento de 2 quartos com vista panorâmica para a praia de Copacabana. Totalmente reformado, com cozinha equipada, ar-condicionado em todos os cômodos e Wi-Fi de alta velocidade. A 2 minutos a pé da praia e próximo ao metrô.',
    propertyType: 'apartment',
    roomType: 'entire_place',
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    pricePerNight: 350,
    cleaningFee: 120,
    currency: 'BRL',
    minimumNights: 2,
    maximumNights: 30,
    checkInTime: '15:00',
    checkOutTime: '11:00',
    cancellationPolicy: 'moderate',
    instantBooking: true,
    status: 'active',
    averageRating: 4.85,
    totalReviews: 127,
    viewsCount: 3420,
    address: {
      street: 'Av. Atlântica',
      number: '1200',
      complement: 'Apt 801',
      neighborhood: 'Copacabana',
      city: 'Rio de Janeiro',
      state: 'RJ',
      country: 'Brasil',
      zipCode: '22021-000',
      latitude: -22.9711,
      longitude: -43.1822,
    },
    photos: [
      {
        id: 'ph1-1',
        url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
        caption: 'Sala de estar',
        order: 1,
      },
      {
        id: 'ph1-2',
        url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
        caption: 'Quarto principal',
        order: 2,
      },
      {
        id: 'ph1-3',
        url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
        caption: 'Cozinha',
        order: 3,
      },
      {
        id: 'ph1-4',
        url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
        caption: 'Vista da praia',
        order: 4,
      },
    ],
    amenities: [
      'Wi-Fi',
      'Ar-condicionado',
      'Cozinha',
      'TV',
      'Máquina de lavar',
      'Elevador',
      'Vista para o mar',
    ],
    reviews: [
      {
        id: 'r1-1',
        userId: 'u3-guest-maria',
        userName: 'Maria S.',
        userPhoto:
          'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100',
        rating: 5,
        comment:
          'Apartamento incrível! A vista é de tirar o fôlego. Tudo muito limpo e organizado.',
        createdAt: '2026-01-20T10:00:00Z',
      },
      {
        id: 'r1-2',
        userId: 'u4-guest-pedro',
        userName: 'Pedro O.',
        userPhoto:
          'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100',
        rating: 4.5,
        comment: 'Ótima localização e apartamento bem equipado. Recomendo!',
        createdAt: '2026-01-10T14:00:00Z',
      },
    ],
    createdAt: '2023-03-15T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'p2',
    hostId: 'u1-host-ana',
    title: 'Casa Charmosa em Santa Teresa com Piscina',
    description:
      'Casa colonial restaurada no coração de Santa Teresa. 3 quartos, piscina privativa, jardim tropical e vista para o Cristo Redentor. Perfeita para famílias ou grupos de amigos.',
    propertyType: 'house',
    roomType: 'entire_place',
    maxGuests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    pricePerNight: 580,
    cleaningFee: 200,
    currency: 'BRL',
    minimumNights: 3,
    maximumNights: 14,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    cancellationPolicy: 'strict',
    instantBooking: false,
    status: 'active',
    averageRating: 4.92,
    totalReviews: 89,
    viewsCount: 2150,
    address: {
      street: 'Rua Almirante Alexandrino',
      number: '450',
      neighborhood: 'Santa Teresa',
      city: 'Rio de Janeiro',
      state: 'RJ',
      country: 'Brasil',
      zipCode: '20241-260',
      latitude: -22.9219,
      longitude: -43.1842,
    },
    photos: [
      {
        id: 'ph2-1',
        url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
        caption: 'Fachada',
        order: 1,
      },
      {
        id: 'ph2-2',
        url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
        caption: 'Piscina',
        order: 2,
      },
      {
        id: 'ph2-3',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
        caption: 'Sala',
        order: 3,
      },
      {
        id: 'ph2-4',
        url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
        caption: 'Jardim',
        order: 4,
      },
    ],
    amenities: [
      'Wi-Fi',
      'Piscina',
      'Cozinha',
      'Estacionamento',
      'Jardim',
      'Churrasqueira',
      'Vista panorâmica',
      'Ar-condicionado',
    ],
    reviews: [
      {
        id: 'r2-1',
        userId: 'u3-guest-maria',
        userName: 'Maria S.',
        rating: 5,
        comment:
          'A casa é um sonho! Piscina maravilhosa e a vista para o Cristo é inesquecível.',
        createdAt: '2025-12-15T10:00:00Z',
      },
    ],
    createdAt: '2023-05-20T10:00:00Z',
    updatedAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'p3',
    hostId: 'u2-host-carlos',
    title: 'Studio Moderno na Vila Madalena',
    description:
      'Studio compacto e moderno no coração da Vila Madalena. Ideal para viajantes solo ou casais. Próximo a bares, restaurantes e galerias de arte. Decoração contemporânea e tudo que você precisa.',
    propertyType: 'studio',
    roomType: 'entire_place',
    maxGuests: 2,
    bedrooms: 0,
    beds: 1,
    bathrooms: 1,
    pricePerNight: 180,
    cleaningFee: 80,
    currency: 'BRL',
    minimumNights: 1,
    maximumNights: 30,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    cancellationPolicy: 'flexible',
    instantBooking: true,
    status: 'active',
    averageRating: 4.7,
    totalReviews: 203,
    viewsCount: 5100,
    address: {
      street: 'Rua Aspicuelta',
      number: '88',
      complement: 'Apt 42',
      neighborhood: 'Vila Madalena',
      city: 'São Paulo',
      state: 'SP',
      country: 'Brasil',
      zipCode: '05433-010',
      latitude: -23.5535,
      longitude: -46.6912,
    },
    photos: [
      {
        id: 'ph3-1',
        url: 'https://images.unsplash.com/photo-1630699144867-37acec97df5a?w=800',
        caption: 'Studio',
        order: 1,
      },
      {
        id: 'ph3-2',
        url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
        caption: 'Área de trabalho',
        order: 2,
      },
      {
        id: 'ph3-3',
        url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800',
        caption: 'Banheiro',
        order: 3,
      },
    ],
    amenities: [
      'Wi-Fi',
      'Ar-condicionado',
      'Cozinha compacta',
      'TV',
      'Máquina de lavar',
      'Área de trabalho',
    ],
    reviews: [
      {
        id: 'r3-1',
        userId: 'u4-guest-pedro',
        userName: 'Pedro O.',
        rating: 5,
        comment:
          'Perfeito para trabalho remoto! Wi-Fi excelente e localização incrível.',
        createdAt: '2026-01-25T10:00:00Z',
      },
      {
        id: 'r3-2',
        userId: 'u3-guest-maria',
        userName: 'Maria S.',
        rating: 4.5,
        comment: 'Espaço bem aproveitado, limpo e aconchegante. Voltarei!',
        createdAt: '2025-11-20T10:00:00Z',
      },
    ],
    createdAt: '2023-08-10T10:00:00Z',
    updatedAt: '2026-01-30T10:00:00Z',
  },
  {
    id: 'p4',
    hostId: 'u2-host-carlos',
    title: 'Chalé Aconchegante em Gramado',
    description:
      'Chalé de madeira com lareira, perfeito para o inverno gaúcho. 2 quartos, sala com lareira, cozinha completa e varanda com vista para o vale. A 10 minutos do centro de Gramado.',
    propertyType: 'house',
    roomType: 'entire_place',
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1.5,
    pricePerNight: 420,
    cleaningFee: 150,
    currency: 'BRL',
    minimumNights: 2,
    maximumNights: 14,
    checkInTime: '15:00',
    checkOutTime: '11:00',
    cancellationPolicy: 'moderate',
    instantBooking: true,
    status: 'active',
    averageRating: 4.95,
    totalReviews: 156,
    viewsCount: 4200,
    address: {
      street: 'Estrada do Vale',
      number: '320',
      neighborhood: 'Planalto',
      city: 'Gramado',
      state: 'RS',
      country: 'Brasil',
      zipCode: '95670-000',
      latitude: -29.3725,
      longitude: -50.8737,
    },
    photos: [
      {
        id: 'ph4-1',
        url: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800',
        caption: 'Chalé exterior',
        order: 1,
      },
      {
        id: 'ph4-2',
        url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
        caption: 'Sala com lareira',
        order: 2,
      },
      {
        id: 'ph4-3',
        url: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800',
        caption: 'Quarto',
        order: 3,
      },
      {
        id: 'ph4-4',
        url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
        caption: 'Varanda',
        order: 4,
      },
    ],
    amenities: [
      'Wi-Fi',
      'Lareira',
      'Cozinha',
      'Estacionamento',
      'Aquecimento',
      'TV',
      'Churrasqueira',
      'Vista para o vale',
    ],
    reviews: [
      {
        id: 'r4-1',
        userId: 'u3-guest-maria',
        userName: 'Maria S.',
        rating: 5,
        comment:
          'Lugar mágico! A lareira é um charme e a vista do vale é espetacular.',
        createdAt: '2026-01-05T10:00:00Z',
      },
    ],
    createdAt: '2023-04-01T10:00:00Z',
    updatedAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'p5',
    hostId: 'u1-host-ana',
    title: 'Quarto Privativo em Ipanema',
    description:
      'Quarto privativo confortável em apartamento compartilhado em Ipanema. Banheiro privativo, café da manhã incluso. A 5 minutos a pé da praia. Perfeito para viajantes solo.',
    propertyType: 'room',
    roomType: 'private_room',
    maxGuests: 1,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    pricePerNight: 120,
    cleaningFee: 50,
    currency: 'BRL',
    minimumNights: 1,
    maximumNights: 30,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    cancellationPolicy: 'flexible',
    instantBooking: true,
    status: 'active',
    averageRating: 4.6,
    totalReviews: 78,
    viewsCount: 1890,
    address: {
      street: 'Rua Visconde de Pirajá',
      number: '580',
      complement: 'Apt 302',
      neighborhood: 'Ipanema',
      city: 'Rio de Janeiro',
      state: 'RJ',
      country: 'Brasil',
      zipCode: '22410-002',
      latitude: -22.9838,
      longitude: -43.2096,
    },
    photos: [
      {
        id: 'ph5-1',
        url: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
        caption: 'Quarto',
        order: 1,
      },
      {
        id: 'ph5-2',
        url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800',
        caption: 'Banheiro',
        order: 2,
      },
    ],
    amenities: [
      'Wi-Fi',
      'Ar-condicionado',
      'Café da manhã',
      'Banheiro privativo',
      'TV',
    ],
    reviews: [
      {
        id: 'r5-1',
        userId: 'u4-guest-pedro',
        userName: 'Pedro O.',
        rating: 4.5,
        comment:
          'Quarto confortável, café da manhã delicioso. Ana é uma anfitriã incrível!',
        createdAt: '2026-01-28T10:00:00Z',
      },
    ],
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2026-01-30T10:00:00Z',
  },
  {
    id: 'p6',
    hostId: 'u2-host-carlos',
    title: 'Apartamento Luxo na Av. Paulista',
    description:
      'Apartamento de alto padrão na Av. Paulista com 3 quartos, 2 banheiros, sala ampla e cozinha gourmet. Vista para o skyline de São Paulo. Condomínio com academia e piscina.',
    propertyType: 'apartment',
    roomType: 'entire_place',
    maxGuests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    pricePerNight: 650,
    cleaningFee: 200,
    currency: 'BRL',
    minimumNights: 2,
    maximumNights: 30,
    checkInTime: '15:00',
    checkOutTime: '11:00',
    cancellationPolicy: 'strict',
    instantBooking: false,
    status: 'active',
    averageRating: 4.88,
    totalReviews: 64,
    viewsCount: 2800,
    address: {
      street: 'Av. Paulista',
      number: '1578',
      complement: 'Apt 2201',
      neighborhood: 'Bela Vista',
      city: 'São Paulo',
      state: 'SP',
      country: 'Brasil',
      zipCode: '01310-200',
      latitude: -23.5614,
      longitude: -46.6558,
    },
    photos: [
      {
        id: 'ph6-1',
        url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
        caption: 'Sala',
        order: 1,
      },
      {
        id: 'ph6-2',
        url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
        caption: 'Quarto master',
        order: 2,
      },
      {
        id: 'ph6-3',
        url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
        caption: 'Cozinha gourmet',
        order: 3,
      },
      {
        id: 'ph6-4',
        url: 'https://images.unsplash.com/photo-1600573472556-e636c2acda9e?w=800',
        caption: 'Vista noturna',
        order: 4,
      },
    ],
    amenities: [
      'Wi-Fi',
      'Ar-condicionado',
      'Cozinha gourmet',
      'TV 65"',
      'Máquina de lavar',
      'Academia',
      'Piscina',
      'Estacionamento',
      'Portaria 24h',
    ],
    reviews: [
      {
        id: 'r6-1',
        userId: 'u3-guest-maria',
        userName: 'Maria S.',
        rating: 5,
        comment:
          'Apartamento impecável! Vista deslumbrante e muito bem equipado.',
        createdAt: '2025-12-20T10:00:00Z',
      },
    ],
    createdAt: '2023-09-01T10:00:00Z',
    updatedAt: '2026-01-25T10:00:00Z',
  },
  {
    id: 'p7',
    hostId: 'u1-host-ana',
    title: 'Casa de Praia em Florianópolis - Campeche',
    description:
      'Casa espaçosa a 300m da Praia do Campeche. 4 quartos, área gourmet com churrasqueira, jardim e garagem. Ideal para férias em família. Próximo a trilhas e lagoa.',
    propertyType: 'house',
    roomType: 'entire_place',
    maxGuests: 8,
    bedrooms: 4,
    beds: 5,
    bathrooms: 3,
    pricePerNight: 480,
    cleaningFee: 180,
    currency: 'BRL',
    minimumNights: 3,
    maximumNights: 30,
    checkInTime: '14:00',
    checkOutTime: '10:00',
    cancellationPolicy: 'moderate',
    instantBooking: true,
    status: 'active',
    averageRating: 4.78,
    totalReviews: 95,
    viewsCount: 3100,
    address: {
      street: 'Rua das Gaivotas',
      number: '150',
      neighborhood: 'Campeche',
      city: 'Florianópolis',
      state: 'SC',
      country: 'Brasil',
      zipCode: '88063-100',
      latitude: -27.6755,
      longitude: -48.4773,
    },
    photos: [
      {
        id: 'ph7-1',
        url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
        caption: 'Fachada',
        order: 1,
      },
      {
        id: 'ph7-2',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
        caption: 'Sala',
        order: 2,
      },
      {
        id: 'ph7-3',
        url: 'https://images.unsplash.com/photo-1600573472556-e636c2acda9e?w=800',
        caption: 'Área gourmet',
        order: 3,
      },
      {
        id: 'ph7-4',
        url: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=800',
        caption: 'Praia do Campeche',
        order: 4,
      },
    ],
    amenities: [
      'Wi-Fi',
      'Cozinha',
      'Churrasqueira',
      'Estacionamento',
      'Jardim',
      'Ar-condicionado',
      'Máquina de lavar',
      'Ventilador',
    ],
    reviews: [
      {
        id: 'r7-1',
        userId: 'u4-guest-pedro',
        userName: 'Pedro O.',
        rating: 5,
        comment:
          'Casa perfeita para família! Praia a poucos passos e muito espaço.',
        createdAt: '2026-01-15T10:00:00Z',
      },
      {
        id: 'r7-2',
        userId: 'u3-guest-maria',
        userName: 'Maria S.',
        rating: 4.5,
        comment: 'Adoramos! Casa limpa e bem localizada. Voltaremos!',
        createdAt: '2025-10-10T10:00:00Z',
      },
    ],
    createdAt: '2023-11-01T10:00:00Z',
    updatedAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'p8',
    hostId: 'u2-host-carlos',
    title: 'Loft Industrial nos Jardins',
    description:
      'Loft com design industrial no bairro dos Jardins. Pé-direito duplo, tijolinho aparente, iluminação natural. Próximo à Rua Oscar Freire e restaurantes renomados.',
    propertyType: 'apartment',
    roomType: 'entire_place',
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    pricePerNight: 280,
    cleaningFee: 100,
    currency: 'BRL',
    minimumNights: 1,
    maximumNights: 30,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    cancellationPolicy: 'flexible',
    instantBooking: true,
    status: 'active',
    averageRating: 4.82,
    totalReviews: 142,
    viewsCount: 3800,
    address: {
      street: 'Rua Oscar Freire',
      number: '240',
      complement: 'Loft 5',
      neighborhood: 'Jardins',
      city: 'São Paulo',
      state: 'SP',
      country: 'Brasil',
      zipCode: '01426-000',
      latitude: -23.5625,
      longitude: -46.6691,
    },
    photos: [
      {
        id: 'ph8-1',
        url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
        caption: 'Loft',
        order: 1,
      },
      {
        id: 'ph8-2',
        url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
        caption: 'Área de estar',
        order: 2,
      },
      {
        id: 'ph8-3',
        url: 'https://images.unsplash.com/photo-1630699144867-37acec97df5a?w=800',
        caption: 'Mezanino',
        order: 3,
      },
    ],
    amenities: [
      'Wi-Fi',
      'Ar-condicionado',
      'Cozinha',
      'TV',
      'Máquina de lavar',
      'Área de trabalho',
      'Portaria 24h',
    ],
    reviews: [
      {
        id: 'r8-1',
        userId: 'u3-guest-maria',
        userName: 'Maria S.',
        rating: 5,
        comment: 'Design incrível! O loft é ainda mais bonito que nas fotos.',
        createdAt: '2026-02-01T10:00:00Z',
      },
    ],
    createdAt: '2024-02-15T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'p9',
    hostId: 'u1-host-ana',
    title: 'Pousada Rústica no Pelourinho - Salvador',
    description:
      'Quarto charmoso em pousada no coração do Pelourinho. Arquitetura colonial, café da manhã baiano incluso. A poucos passos do Largo do Pelourinho e da Igreja de São Francisco.',
    propertyType: 'room',
    roomType: 'private_room',
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    pricePerNight: 150,
    cleaningFee: 0,
    currency: 'BRL',
    minimumNights: 1,
    maximumNights: 14,
    checkInTime: '13:00',
    checkOutTime: '11:00',
    cancellationPolicy: 'flexible',
    instantBooking: true,
    status: 'active',
    averageRating: 4.65,
    totalReviews: 210,
    viewsCount: 4500,
    address: {
      street: 'Rua Gregório de Matos',
      number: '28',
      neighborhood: 'Pelourinho',
      city: 'Salvador',
      state: 'BA',
      country: 'Brasil',
      zipCode: '40026-010',
      latitude: -12.9714,
      longitude: -38.5124,
    },
    photos: [
      {
        id: 'ph9-1',
        url: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
        caption: 'Quarto',
        order: 1,
      },
      {
        id: 'ph9-2',
        url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
        caption: 'Pousada',
        order: 2,
      },
      {
        id: 'ph9-3',
        url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800',
        caption: 'Banheiro',
        order: 3,
      },
    ],
    amenities: [
      'Wi-Fi',
      'Café da manhã',
      'Ventilador',
      'TV',
      'Banheiro privativo',
      'Recepção 24h',
    ],
    reviews: [
      {
        id: 'r9-1',
        userId: 'u4-guest-pedro',
        userName: 'Pedro O.',
        rating: 4.5,
        comment:
          'Localização perfeita no Pelourinho! Café da manhã incrível com acarajé.',
        createdAt: '2026-01-18T10:00:00Z',
      },
      {
        id: 'r9-2',
        userId: 'u3-guest-maria',
        userName: 'Maria S.',
        rating: 4,
        comment: 'Lugar com muito charme. O quarto é pequeno mas confortável.',
        createdAt: '2025-09-05T10:00:00Z',
      },
    ],
    createdAt: '2024-05-01T10:00:00Z',
    updatedAt: '2026-01-25T10:00:00Z',
  },
  {
    id: 'p10',
    hostId: 'u2-host-carlos',
    title: 'Villa com Vista para o Mar em Jurerê',
    description:
      'Villa luxuosa em Jurerê Internacional. 5 suítes, piscina de borda infinita, sauna, espaço gourmet completo. A 200m da praia. Ideal para eventos e grupos grandes.',
    propertyType: 'villa',
    roomType: 'entire_place',
    maxGuests: 10,
    bedrooms: 5,
    beds: 6,
    bathrooms: 5,
    pricePerNight: 1200,
    cleaningFee: 400,
    currency: 'BRL',
    minimumNights: 3,
    maximumNights: 14,
    checkInTime: '16:00',
    checkOutTime: '11:00',
    cancellationPolicy: 'strict',
    instantBooking: false,
    status: 'active',
    averageRating: 4.97,
    totalReviews: 32,
    viewsCount: 6200,
    address: {
      street: 'Rua das Algas',
      number: '88',
      neighborhood: 'Jurerê Internacional',
      city: 'Florianópolis',
      state: 'SC',
      country: 'Brasil',
      zipCode: '88053-300',
      latitude: -27.4355,
      longitude: -48.4912,
    },
    photos: [
      {
        id: 'ph10-1',
        url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
        caption: 'Villa',
        order: 1,
      },
      {
        id: 'ph10-2',
        url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
        caption: 'Piscina infinita',
        order: 2,
      },
      {
        id: 'ph10-3',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
        caption: 'Suíte master',
        order: 3,
      },
      {
        id: 'ph10-4',
        url: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800',
        caption: 'Espaço gourmet',
        order: 4,
      },
      {
        id: 'ph10-5',
        url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
        caption: 'Vista da praia',
        order: 5,
      },
    ],
    amenities: [
      'Wi-Fi',
      'Piscina',
      'Sauna',
      'Cozinha gourmet',
      'Estacionamento',
      'Ar-condicionado',
      'Churrasqueira',
      'TV',
      'Jardim',
      'Segurança 24h',
    ],
    reviews: [
      {
        id: 'r10-1',
        userId: 'u3-guest-maria',
        userName: 'Maria S.',
        rating: 5,
        comment:
          'Villa dos sonhos! Tudo perfeito, desde a piscina até o atendimento.',
        createdAt: '2026-01-30T10:00:00Z',
      },
    ],
    createdAt: '2024-06-15T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'p11',
    hostId: 'u1-host-ana',
    title: 'Apartamento Compacto no Centro de BH',
    description:
      'Apartamento funcional no centro de Belo Horizonte. Próximo à Praça da Liberdade, Mercado Central e vida cultural. Ideal para viagens de negócios ou turismo urbano.',
    propertyType: 'apartment',
    roomType: 'entire_place',
    maxGuests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    pricePerNight: 140,
    cleaningFee: 60,
    currency: 'BRL',
    minimumNights: 1,
    maximumNights: 30,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    cancellationPolicy: 'flexible',
    instantBooking: true,
    status: 'active',
    averageRating: 4.55,
    totalReviews: 167,
    viewsCount: 2900,
    address: {
      street: 'Av. Augusto de Lima',
      number: '785',
      complement: 'Apt 504',
      neighborhood: 'Centro',
      city: 'Belo Horizonte',
      state: 'MG',
      country: 'Brasil',
      zipCode: '30190-001',
      latitude: -19.9191,
      longitude: -43.9378,
    },
    photos: [
      {
        id: 'ph11-1',
        url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
        caption: 'Sala',
        order: 1,
      },
      {
        id: 'ph11-2',
        url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
        caption: 'Quarto',
        order: 2,
      },
      {
        id: 'ph11-3',
        url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
        caption: 'Cozinha',
        order: 3,
      },
    ],
    amenities: [
      'Wi-Fi',
      'Ar-condicionado',
      'Cozinha',
      'TV',
      'Elevador',
      'Portaria 24h',
    ],
    reviews: [
      {
        id: 'r11-1',
        userId: 'u4-guest-pedro',
        userName: 'Pedro O.',
        rating: 4.5,
        comment: 'Ótimo custo-benefício no centro de BH. Perto de tudo!',
        createdAt: '2026-01-22T10:00:00Z',
      },
    ],
    createdAt: '2024-09-01T10:00:00Z',
    updatedAt: '2026-01-28T10:00:00Z',
  },
  {
    id: 'p12',
    hostId: 'u2-host-carlos',
    title: 'Cabana na Serra Gaúcha - Canela',
    description:
      'Cabana de madeira em meio à natureza na Serra Gaúcha. Lareira, banheira de hidromassagem, deck com vista para o vale. Experiência romântica perfeita para casais.',
    propertyType: 'house',
    roomType: 'entire_place',
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    pricePerNight: 380,
    cleaningFee: 120,
    currency: 'BRL',
    minimumNights: 2,
    maximumNights: 7,
    checkInTime: '15:00',
    checkOutTime: '11:00',
    cancellationPolicy: 'moderate',
    instantBooking: true,
    status: 'active',
    averageRating: 4.93,
    totalReviews: 88,
    viewsCount: 3500,
    address: {
      street: 'Estrada da Ferradura',
      number: '500',
      neighborhood: 'Ferradura',
      city: 'Canela',
      state: 'RS',
      country: 'Brasil',
      zipCode: '95680-000',
      latitude: -29.3465,
      longitude: -50.8259,
    },
    photos: [
      {
        id: 'ph12-1',
        url: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800',
        caption: 'Cabana',
        order: 1,
      },
      {
        id: 'ph12-2',
        url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
        caption: 'Interior',
        order: 2,
      },
      {
        id: 'ph12-3',
        url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
        caption: 'Banheira',
        order: 3,
      },
    ],
    amenities: [
      'Wi-Fi',
      'Lareira',
      'Banheira de hidromassagem',
      'Cozinha',
      'Estacionamento',
      'Aquecimento',
      'Deck',
      'Vista para o vale',
    ],
    reviews: [
      {
        id: 'r12-1',
        userId: 'u3-guest-maria',
        userName: 'Maria S.',
        rating: 5,
        comment:
          'Experiência romântica perfeita! A banheira com vista para o vale é inesquecível.',
        createdAt: '2026-01-12T10:00:00Z',
      },
    ],
    createdAt: '2024-04-20T10:00:00Z',
    updatedAt: '2026-01-15T10:00:00Z',
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b1',
    propertyId: 'p1',
    guestId: 'u3-guest-maria',
    hostId: 'u1-host-ana',
    checkIn: '2026-03-10',
    checkOut: '2026-03-15',
    guests: 2,
    totalNights: 5,
    pricePerNight: 350,
    cleaningFee: 120,
    serviceFee: 175,
    totalPrice: 2045,
    currency: 'BRL',
    status: 'confirmed',
    propertyTitle: 'Apartamento com Vista para o Mar em Copacabana',
    propertyPhoto:
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'b2',
    propertyId: 'p4',
    guestId: 'u4-guest-pedro',
    hostId: 'u2-host-carlos',
    checkIn: '2026-02-20',
    checkOut: '2026-02-24',
    guests: 2,
    totalNights: 4,
    pricePerNight: 420,
    cleaningFee: 150,
    serviceFee: 168,
    totalPrice: 1998,
    currency: 'BRL',
    status: 'pending',
    propertyTitle: 'Chalé Aconchegante em Gramado',
    propertyPhoto:
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800',
    createdAt: '2026-02-05T14:00:00Z',
    updatedAt: '2026-02-05T14:00:00Z',
  },
  {
    id: 'b3',
    propertyId: 'p3',
    guestId: 'u3-guest-maria',
    hostId: 'u2-host-carlos',
    checkIn: '2025-12-01',
    checkOut: '2025-12-05',
    guests: 1,
    totalNights: 4,
    pricePerNight: 180,
    cleaningFee: 80,
    serviceFee: 72,
    totalPrice: 872,
    currency: 'BRL',
    status: 'completed',
    propertyTitle: 'Studio Moderno na Vila Madalena',
    propertyPhoto:
      'https://images.unsplash.com/photo-1630699144867-37acec97df5a?w=800',
    createdAt: '2025-11-15T10:00:00Z',
    updatedAt: '2025-12-06T10:00:00Z',
  },
];
